name: '$(Build.DefinitionName)_$(Build.BuildId)'

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:


  - task: Checkout@1
  - script: |
      echo "Running existing Docker image"
      echo $PAPERAPIKEY
      docker run -p 127.0.0.1:8080:8080 naegerr/tradingbot:82 -e APIKEY -e PAPERAPIKEY -e PAPERSECRET -e SECRET tradingbot
    displayName: 'Run Docker Image'
    condition: 
