name: '$(Build.DefinitionName)_$(Build.BuildId)'

trigger: none  # no automatic trigger

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Docker@2
    inputs:
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      repository: 'naegerr/tradingbot'
      containerRegistry: 'Tradingbot'
      tags: |
        $(Build.BuildId)
