name: '$(Build.DefinitionName)_$(Build.BuildId)'

trigger: none  # no automatic trigger

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Docker@2
    inputs:
      command: build
      Dockerfile: '**/Dockerfile'
      tags: |
        $(Build.BuildId)
        latest

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)  # Path to the directory where the image is built
      ArtifactName: 'docker-image'
      publishLocation: 'Container'