name: '$(Build.DefinitionName)_$(Build.BuildId)'

trigger:
- main

variables:
  group: AlpacaAccess
  dockerImage: naegerr/tradingbot:latest

pool:
  vmImage: 'ubuntu-latest'


steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'TradingbotSubscription(f2d42c0b-0993-4ce2-b0c2-9a304c1092d9)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "Logged in to Azure"

  # Deploy container image to Azure Web App
  - task: AzureContainerApps@1
    inputs:
      azureSubscription: 'TradingbotSubscription(f2d42c0b-0993-4ce2-b0c2-9a304c1092d9)'
      imageToDeploy: 'naegerr/tradingbot:82'
      containerAppName: 'tradingbotcontainer'
      environmentVariables: |
        secretref:PAPERSECRET=$(PAPERSECRET)
        secretref:PAPERAPIKEY=$(PAPERAPIKEY)
        secretref:APIKEY=$(APIKEY)
        secretref:SECRET=$(SECRET)
