name: '$(Build.DefinitionName)_$(Build.BuildId)'

trigger:
- main

variables:
  APIKEY: $(APIKEY)
  PAPERAPIKEY: $(PAPERAPIKEY)
  PAPERSECRET: $(PAPERSECRET)
  SECRET: $(SECRET)


pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Docker@2
    displayName: 'Login to Docker Hub' # probably not required
    inputs:
      command: 'login'
      containerRegistry: 'Tradingbot'
  - task: Checkout@1
  - script: |
      echo "Running existing Docker image"
      docker run -p 127.0.0.1:8080:8080 naegerr/tradingbot:82 -e APIKEY -e PAPERAPIKEY -e PAPERSECRET -e SECRET tradingbot
    displayName: 'Run Docker Image'