trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "Starting the server..."
    chmod +x gradlew
    ./gradlew clean build
    nohup ./gradlew run > server.log 2>&1 & 
    sleep 10  # Wait 10 seconds for the server to start
    echo "Server started successfully!"
  displayName: 'Start the server'

- script: |
    echo "Running tests..."
    ./gradlew test
  displayName: 'Run Tests'

- task: Gradle@4
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
