name: '$(Build.DefinitionName)_$(Build.BuildId)'

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: AlpacaAccess

steps:
  - task: Docker@2
    displayName: 'Login to Docker Hub'
    inputs:
      command: 'login'
      containerRegistry: 'Tradingbot'
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "Running existing Docker image"
        docker run -p 127.0.0.1:8080:8080 `
          -e APIKEY=$env:APIKEY `
          -e PAPERAPIKEY=$env:PAPERAPIKEY `
          -e PAPERSECRET=$env:PAPERSECRET `
          -e SECRET=$env:SECRET `
          naegerr/tradingbot:82 tradingbot
    displayName: 'Run Docker Image'
