name: '$(Build.DefinitionName)_$(Build.BuildId)'

trigger:
- main

variables:
  group: AlpacaAccess
  dockerImage: naegerr/tradingbot:latest

pool:
  vmImage: 'ubuntu-latest'


steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'TradingbotSubscription(f2d42c0b-0993-4ce2-b0c2-9a304c1092d9)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "Logged in to Azure"

  # Deploy container image to Azure Web App
  - task: AzureWebApp@1
    inputs:
      appType: 'webAppLinux'
      azureSubscription: 'TradingbotSubscription(f2d42c0b-0993-4ce2-b0c2-9a304c1092d9)'
      resourceGroupName: 'TradingBot'
      appName: 'tradingbot'
      package: '$(System.DefaultWorkingDirectory)/**/*.zip'
      appSettings: |
        PAPERSECRET=$(PAPERSECRET)
        PAPERAPIKEY=$(PAPERAPIKEY)
        APIKEY=$(APIKEY)
        SECRET=$(SECRET)
