FROM gradle:8.13.0-jdk17-corretto-al2023

WORKDIR /home/gradle/app

# Install tools you might need
RUN yum install -y bash
EXPOSE 8081

# Default command (can be overridden by docker run)
CMD ["bash"]
