version: '3.8'

services:
  deploy:
    build:
      context: ..
      dockerfile: Docker/Dockerfile.deploy
    container_name: deploy-container
    ports:
      - "8080:8080"
    networks:
      - tradingBotNetwork
  test:
    build:
      context: ..
      dockerfile: Docker/Dockerfile.test
    depends_on:
      - deploy

    container_name: test-container
    networks:
      - tradingBotNetwork
    command: ["curl", "http://deploy:8080"]

networks:
  tradingBotNetwork:
    driver: bridge
