# Stage 1: Cache Gradle dependencies
FROM gradle:8.13.0-jdk17-corretto-al2023 as cache

ENV GRADLE_USER_HOME_CACHE=/home/gradle/cache_home
RUN echo "GRADLE_USER_HOME=$GRADLE_USER_HOME_CACHE"
RUN mkdir -p $GRADLE_USER_HOME_CACHE
ENV GRADLE_USER_HOME=/home/gradle/.gradle
RUN mkdir -p $GRADLE_USER_HOME
COPY build.gradle.* gradle.properties /home/gradle/app/
COPY ../gradle /home/gradle/app/gradle
WORKDIR /home/gradle/app
RUN gradle clean build -i --stacktrace

# Stage 2: Test
FROM gradle:8.13.0-jdk17-corretto-al2023  AS test

ENV REPORT_DIR=/app/reports
COPY --from=cache /home/gradle/cache_home /home/gradle/.gradle
COPY .. /usr/src/app/
WORKDIR /usr/src/app
COPY --chown=gradle:gradle .. /home/gradle/src
WORKDIR /home/gradle/src

RUN gradle test              # Runs tests
RUN gradle koverHtmlReport   # Report tests

RUN WORKDIR $REPORT_DIR
#COPY /home/gradle/src/build/reports/tests/test $REPORT_DIR
#COPY /home/gradle/src/build/reports/kover      $REPORT_DIR